
services:

  ###################################################
  # Traefik Reverse Proxy
  ###################################################
  proxy:
    image: traefik:v3.6
    command:
      - --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###################################################
  # Backend API
  ###################################################
  backend:
    build:
      context: ./
      target: backend-dev
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
      labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 3000
  ###################################################
  # Client (React + Vite)
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
    labels:
      traefik.http.routers.client.rule: PathPrefix(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5173

  ###################################################
  # PostgreSQL Database
  ###################################################
  postgres:
    image: postgres
    restart: always
    env_file:
      -..env
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports: 
        - "${POSTGRES_PORT}:5432"

  
###################################################
# Volumes
###################################################
volumes:
  db-data: {}
