###################################################
# Docker Compose for Node + React + PostgreSQL + Traefik
###################################################
services:

  ###################################################
  # Reverse proxy (Traefik)
  ###################################################
  proxy:
    image: traefik:v3.6
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###################################################
  # Backend API (Node.js)
  ###################################################
  backend:
    build:
      context: ./
      target: backend-dev
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short 
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 3000

  ###################################################
  # Client (React)
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5173

  ###################################################
  # PostgreSQL Database
  ###################################################
  postgres:
    image: postgres:15
    volumes:
      - todo-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d todos"]
      interval: 5s
      timeout: 5s
      retries: 5

  ###################################################
  # pgAdmin (PostgreSQL GUI)
  ###################################################
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: secret
    labels:
      traefik.http.routers.pgadmin.rule: Host(`db.localhost`)
      traefik.http.services.pgadmin.loadbalancer.server.port: 80

###################################################
# Volumes
###################################################
volumes:
  todo-postgres-data:
